/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MenuPrincipal;
//import MenuPrincipal.LoginFrame;
import Consulta.BalanzaG;
import Consulta.Balanzacomprobacion;
import Consulta.Ccuenta;
import Consulta.CdocumentoFrame;
import Consulta.CusuarioFrame;
import Consulta.TipoDcumento;
import Consulta.Trans_por_tipo_documento;
import Consulta.trasnacionfecha;
import Consulta.trasnasacionporrango;
import Mantenimiento.*;
import Movimiento.TrasaccionesFrame;
import Procesos.Cierre_de_diario;

import java.awt.Color;


/**
 *
 * @author Dalvi
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        this.setExtendedState(MenuPrincipal.MAXIMIZED_BOTH);
        userlabel.setForeground(new Color(64,68,237));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        mainpanel = new javax.swing.JPanel();
        userlabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mantenimientoMn = new javax.swing.JMenu();
        usuarioItem = new javax.swing.JMenuItem();
        catalogoItem = new javax.swing.JMenuItem();
        documentoItem = new javax.swing.JMenuItem();
        movimientoMn = new javax.swing.JMenu();
        trasanccionesItem = new javax.swing.JMenuItem();
        procesoMn = new javax.swing.JMenu();
        cierre_diario_fechaItem = new javax.swing.JMenuItem();
        consultaMn = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        CusurioItem = new javax.swing.JMenuItem();
        CcatalogoItem = new javax.swing.JMenuItem();
        CdocumentoItem = new javax.swing.JMenuItem();
        transaccionfecha = new javax.swing.JMenuItem();
        transccionporrango = new javax.swing.JMenuItem();
        transpordoc = new javax.swing.JMenuItem();
        transaccionportipo = new javax.swing.JMenuItem();
        balanzag = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        Salir = new javax.swing.JMenu();
        Cerrar = new javax.swing.JMenuItem();

        jMenu2.setText("jMenu2");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");
        setLocationByPlatform(true);

        mainpanel.setBackground(new java.awt.Color(39, 38, 44));
        mainpanel.setToolTipText("");
        mainpanel.setPreferredSize(new java.awt.Dimension(849, 557));
        mainpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userlabel.setBackground(new java.awt.Color(64, 68, 237));
        userlabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        userlabel.setToolTipText("");
        mainpanel.add(userlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, 300, 70));

        mantenimientoMn.setText("Mantenimiento");

        usuarioItem.setText("Usuarios");
        usuarioItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioItemActionPerformed(evt);
            }
        });
        mantenimientoMn.add(usuarioItem);

        catalogoItem.setText("Catalogo");
        catalogoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catalogoItemActionPerformed(evt);
            }
        });
        mantenimientoMn.add(catalogoItem);

        documentoItem.setText("Documento");
        documentoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                documentoItemActionPerformed(evt);
            }
        });
        mantenimientoMn.add(documentoItem);

        jMenuBar1.add(mantenimientoMn);

        movimientoMn.setText("Movimiento");

        trasanccionesItem.setText("Trasacciones");
        trasanccionesItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trasanccionesItemActionPerformed(evt);
            }
        });
        movimientoMn.add(trasanccionesItem);

        jMenuBar1.add(movimientoMn);

        procesoMn.setText("Procesos");

        cierre_diario_fechaItem.setText("Cierre de Diaro por fecha");
        cierre_diario_fechaItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cierre_diario_fechaItemActionPerformed(evt);
            }
        });
        procesoMn.add(cierre_diario_fechaItem);

        jMenuBar1.add(procesoMn);

        consultaMn.setText("Consultas");

        jMenu1.setText("Consulta de Mantenimiento");

        CusurioItem.setText("Usuario");
        CusurioItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CusurioItemActionPerformed(evt);
            }
        });
        jMenu1.add(CusurioItem);

        CcatalogoItem.setText("Catalogo de Cuenta");
        CcatalogoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CcatalogoItemActionPerformed(evt);
            }
        });
        jMenu1.add(CcatalogoItem);

        CdocumentoItem.setText("Mov. Documento");
        CdocumentoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CdocumentoItemActionPerformed(evt);
            }
        });
        jMenu1.add(CdocumentoItem);

        consultaMn.add(jMenu1);

        transaccionfecha.setText("Transaccion por fecha");
        transaccionfecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaccionfechaActionPerformed(evt);
            }
        });
        consultaMn.add(transaccionfecha);

        transccionporrango.setText("Trasanccion por rango de fecha");
        transccionporrango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transccionporrangoActionPerformed(evt);
            }
        });
        consultaMn.add(transccionporrango);

        transpordoc.setText("Transacciones por documento");
        transpordoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transpordocActionPerformed(evt);
            }
        });
        consultaMn.add(transpordoc);

        transaccionportipo.setText("Transacciones por tipo de documentos");
        transaccionportipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaccionportipoActionPerformed(evt);
            }
        });
        consultaMn.add(transaccionportipo);

        balanzag.setText("Balanza genral ");
        balanzag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanzagActionPerformed(evt);
            }
        });
        consultaMn.add(balanzag);

        jMenuItem2.setText("Balanza de comprobacion ");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        consultaMn.add(jMenuItem2);

        jMenuItem13.setText("Resume de Gasto Generales");
        consultaMn.add(jMenuItem13);

        jMenuBar1.add(consultaMn);

        Salir.setBackground(new java.awt.Color(255, 0, 0));
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        Cerrar.setText("Cerrar");
        Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarActionPerformed(evt);
            }
        });
        Salir.add(Cerrar);

        jMenuBar1.add(Salir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
        );

        mainpanel.getAccessibleContext().setAccessibleName("");

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioItemActionPerformed
        UsuarioFrame U=new UsuarioFrame();
        U.setVisible(true);
       
    }//GEN-LAST:event_usuarioItemActionPerformed

    private void catalogoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catalogoItemActionPerformed
        CatalogoFrame C = new CatalogoFrame();
        C.setVisible(true);
      
    }//GEN-LAST:event_catalogoItemActionPerformed

    private void documentoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_documentoItemActionPerformed
        DocumentoFrame D = new DocumentoFrame();
        D.setVisible(true);
    }//GEN-LAST:event_documentoItemActionPerformed

    private void CusurioItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CusurioItemActionPerformed
        CusuarioFrame cu =new CusuarioFrame();
        cu.setVisible(true);
        
    }//GEN-LAST:event_CusurioItemActionPerformed

    private void CcatalogoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CcatalogoItemActionPerformed
        Ccuenta cu=new Ccuenta();
        cu.setVisible(true);
       
        
    }//GEN-LAST:event_CcatalogoItemActionPerformed

    private void CdocumentoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CdocumentoItemActionPerformed
        CdocumentoFrame cu=new CdocumentoFrame();
        cu.setVisible(true);
        
    }//GEN-LAST:event_CdocumentoItemActionPerformed

    private void trasanccionesItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trasanccionesItemActionPerformed
        TrasaccionesFrame tr=new  TrasaccionesFrame();
        tr.setVisible(true);
    }//GEN-LAST:event_trasanccionesItemActionPerformed

    private void cierre_diario_fechaItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cierre_diario_fechaItemActionPerformed
      Cierre_de_diario tr = new Cierre_de_diario();
      tr.setVisible(true);
      
    }//GEN-LAST:event_cierre_diario_fechaItemActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        
    }//GEN-LAST:event_SalirActionPerformed

    private void CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarActionPerformed
        this.dispose();  
    }//GEN-LAST:event_CerrarActionPerformed

    private void transaccionfechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaccionfechaActionPerformed
        trasnacionfecha tr = new trasnacionfecha (); 
        tr.setVisible(true);
    }//GEN-LAST:event_transaccionfechaActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Balanzacomprobacion tr = new Balanzacomprobacion();
        tr.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void balanzagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanzagActionPerformed
       BalanzaG tr = new  BalanzaG (); 
       tr.setVisible(true);
    }//GEN-LAST:event_balanzagActionPerformed
    
    private void transpordocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transpordocActionPerformed
        Trans_por_tipo_documento tr = new Trans_por_tipo_documento (); 
        tr.setVisible(true);
    }//GEN-LAST:event_transpordocActionPerformed

    private void transccionporrangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transccionporrangoActionPerformed
     trasnasacionporrango tr=new trasnasacionporrango();   
     tr.setVisible(true);
    }//GEN-LAST:event_transccionporrangoActionPerformed

    private void transaccionportipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaccionportipoActionPerformed
      TipoDcumento tr=new TipoDcumento();
      tr.setVisible(true);
    }//GEN-LAST:event_transaccionportipoActionPerformed

   
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CcatalogoItem;
    private javax.swing.JMenuItem CdocumentoItem;
    private javax.swing.JMenuItem Cerrar;
    private javax.swing.JMenuItem CusurioItem;
    private javax.swing.JMenu Salir;
    private javax.swing.JMenuItem balanzag;
    private javax.swing.JMenuItem catalogoItem;
    private javax.swing.JMenuItem cierre_diario_fechaItem;
    private javax.swing.JMenu consultaMn;
    private javax.swing.JMenuItem documentoItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel mainpanel;
    public javax.swing.JMenu mantenimientoMn;
    private javax.swing.JMenu movimientoMn;
    public javax.swing.JMenu procesoMn;
    private javax.swing.JMenuItem transaccionfecha;
    private javax.swing.JMenuItem transaccionportipo;
    private javax.swing.JMenuItem transccionporrango;
    private javax.swing.JMenuItem transpordoc;
    private javax.swing.JMenuItem trasanccionesItem;
    public javax.swing.JLabel userlabel;
    private javax.swing.JMenuItem usuarioItem;
    // End of variables declaration//GEN-END:variables
}
