/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Mantenimiento;

import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.util.Scanner;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import TextPrompt.TextPrompt;
import java.awt.Color;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author Dalvi
 */
public class CatalogoFrame extends javax.swing.JFrame {

    public int tipo;
    ButtonGroup gr = new ButtonGroup();
    private JRadioButton dummyButton = new JRadioButton();

    public CatalogoFrame() {

        gr.add(general);
        gr.add(detallada);
        gr.add(dummyButton);
        initComponents();
        setLocationRelativeTo(null);
        debitotxt.setEditable(false);
        credittxt.setEditable(false);
        balancetxt.setEditable(false);

        TextPrompt p1 = new TextPrompt("Ingrese el numero de cuenta", num_cuentatxt);
        p1.setForeground(Color.white);
        TextPrompt p2 = new TextPrompt("Ingrese el nombre de cuenta", descriptxt);
        p2.setForeground(Color.white);

        TextPrompt p4 = new TextPrompt("Ingrese la cuenta padre", cuenta_padretxt);
        p4.setForeground(Color.white);

    }
    public static String LineaAntigua;
    public boolean Modificar = false;
    public final String accout = "General";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgpanel = new javax.swing.JPanel();
        cabecera = new javax.swing.JPanel();
        encabezadolabel = new javax.swing.JLabel();
        numero_de_cuentalabel = new javax.swing.JLabel();
        num_cuentatxt = new javax.swing.JTextField();
        descriplabel = new javax.swing.JLabel();
        descriptxt = new javax.swing.JTextField();
        tpo_cuentalabel = new javax.swing.JLabel();
        general = new javax.swing.JRadioButton();
        detallada = new javax.swing.JRadioButton();
        nivel_de_cuentalabel = new javax.swing.JLabel();
        cuenta_padre_label = new javax.swing.JLabel();
        grupo_cuenta_label = new javax.swing.JLabel();
        debitolabel = new javax.swing.JLabel();
        creditlabel = new javax.swing.JLabel();
        balancelabel = new javax.swing.JLabel();
        cuenta_padretxt = new javax.swing.JTextField();
        debitotxt = new javax.swing.JTextField();
        credittxt = new javax.swing.JTextField();
        guardarbt = new javax.swing.JButton();
        limpiarbt = new javax.swing.JButton();
        salirbt = new javax.swing.JButton();
        balancetxt = new javax.swing.JTextField();
        status = new javax.swing.JLabel();
        nivelcbx = new javax.swing.JComboBox<>();
        grup_cuentacbx = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Catalogo de Cuenta");
        setLocationByPlatform(true);

        bgpanel.setBackground(new java.awt.Color(39, 38, 44));
        bgpanel.setPreferredSize(new java.awt.Dimension(554, 420));

        cabecera.setBackground(new java.awt.Color(64, 68, 237));
        cabecera.setToolTipText("");

        encabezadolabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        encabezadolabel.setForeground(new java.awt.Color(255, 255, 255));
        encabezadolabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        encabezadolabel.setText("Catàlogo de Cuenta");
        encabezadolabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout cabeceraLayout = new javax.swing.GroupLayout(cabecera);
        cabecera.setLayout(cabeceraLayout);
        cabeceraLayout.setHorizontalGroup(
            cabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cabeceraLayout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(encabezadolabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cabeceraLayout.setVerticalGroup(
            cabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cabeceraLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(encabezadolabel)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        numero_de_cuentalabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        numero_de_cuentalabel.setForeground(new java.awt.Color(255, 255, 255));
        numero_de_cuentalabel.setText("Numero de Cuenta:");

        num_cuentatxt.setBackground(new java.awt.Color(39, 38, 44));
        num_cuentatxt.setForeground(new java.awt.Color(255, 255, 255));
        num_cuentatxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        num_cuentatxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_cuentatxtActionPerformed(evt);
            }
        });

        descriplabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        descriplabel.setForeground(new java.awt.Color(255, 255, 255));
        descriplabel.setText("Descripcion");

        descriptxt.setBackground(new java.awt.Color(39, 38, 44));
        descriptxt.setForeground(new java.awt.Color(255, 255, 255));
        descriptxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        descriptxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriptxtActionPerformed(evt);
            }
        });
        descriptxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                descriptxtKeyTyped(evt);
            }
        });

        tpo_cuentalabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tpo_cuentalabel.setForeground(new java.awt.Color(255, 255, 255));
        tpo_cuentalabel.setText("Tipo de Cuenta");

        general.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        general.setForeground(new java.awt.Color(255, 255, 255));
        general.setText("General");
        general.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generalActionPerformed(evt);
            }
        });
        general.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                generalPropertyChange(evt);
            }
        });

        detallada.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        detallada.setForeground(new java.awt.Color(255, 255, 255));
        detallada.setText("Detalles");
        detallada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detalladaActionPerformed(evt);
            }
        });
        detallada.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                detalladaPropertyChange(evt);
            }
        });

        nivel_de_cuentalabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nivel_de_cuentalabel.setForeground(new java.awt.Color(255, 255, 255));
        nivel_de_cuentalabel.setText("Nivel de Cuenta");

        cuenta_padre_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cuenta_padre_label.setForeground(new java.awt.Color(255, 255, 255));
        cuenta_padre_label.setText("Cuenta Padre");

        grupo_cuenta_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        grupo_cuenta_label.setForeground(new java.awt.Color(255, 255, 255));
        grupo_cuenta_label.setText("Grupo de Cuenta");

        debitolabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        debitolabel.setForeground(new java.awt.Color(255, 255, 255));
        debitolabel.setText("Debito Acumlado");

        creditlabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        creditlabel.setForeground(new java.awt.Color(255, 255, 255));
        creditlabel.setText("Credito acumulado");

        balancelabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        balancelabel.setForeground(new java.awt.Color(255, 255, 255));
        balancelabel.setText("Balance");

        cuenta_padretxt.setBackground(new java.awt.Color(39, 38, 44));
        cuenta_padretxt.setForeground(new java.awt.Color(255, 255, 255));
        cuenta_padretxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        cuenta_padretxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuenta_padretxtActionPerformed(evt);
            }
        });
        cuenta_padretxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cuenta_padretxtKeyTyped(evt);
            }
        });

        debitotxt.setBackground(new java.awt.Color(39, 38, 44));
        debitotxt.setForeground(new java.awt.Color(255, 255, 255));
        debitotxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        debitotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debitotxtActionPerformed(evt);
            }
        });

        credittxt.setBackground(new java.awt.Color(39, 38, 44));
        credittxt.setForeground(new java.awt.Color(255, 255, 255));
        credittxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        credittxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                credittxtActionPerformed(evt);
            }
        });

        guardarbt.setBackground(new java.awt.Color(64, 68, 237));
        guardarbt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        guardarbt.setForeground(new java.awt.Color(255, 255, 255));
        guardarbt.setText("Guardar");
        guardarbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarbtActionPerformed(evt);
            }
        });

        limpiarbt.setBackground(new java.awt.Color(64, 68, 237));
        limpiarbt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        limpiarbt.setForeground(new java.awt.Color(255, 255, 255));
        limpiarbt.setText("Limpiar");
        limpiarbt.setName(""); // NOI18N
        limpiarbt.setPreferredSize(new java.awt.Dimension(79, 27));
        limpiarbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarbtActionPerformed(evt);
            }
        });

        salirbt.setBackground(new java.awt.Color(255, 0, 0));
        salirbt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        salirbt.setForeground(new java.awt.Color(255, 255, 255));
        salirbt.setText("Salir");
        salirbt.setPreferredSize(new java.awt.Dimension(79, 27));
        salirbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirbtActionPerformed(evt);
            }
        });

        balancetxt.setBackground(new java.awt.Color(39, 38, 44));
        balancetxt.setForeground(new java.awt.Color(255, 255, 255));
        balancetxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        balancetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balancetxtActionPerformed(evt);
            }
        });

        status.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        status.setForeground(new java.awt.Color(255, 255, 255));
        status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        status.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        nivelcbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        grup_cuentacbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activos", "Pasivos", "Capital", "Ingresos", "Costos", "Gastos" }));
        grup_cuentacbx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                grup_cuentacbxKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout bgpanelLayout = new javax.swing.GroupLayout(bgpanel);
        bgpanel.setLayout(bgpanelLayout);
        bgpanelLayout.setHorizontalGroup(
            bgpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgpanelLayout.createSequentialGroup()
                .addGroup(bgpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgpanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(guardarbt)
                        .addGap(149, 149, 149)
                        .addComponent(limpiarbt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(156, 156, 156)
                        .addComponent(salirbt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgpanelLayout.createSequentialGroup()
                        .addGroup(bgpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(bgpanelLayout.createSequentialGroup()
                                .addGroup(bgpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(bgpanelLayout.createSequentialGroup()
                                        .addGroup(bgpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(descriplabel)
                                            .addGroup(bgpanelLayout.createSequentialGroup()
                                                .addGap(4, 4, 4)
                                                .addComponent(nivel_de_cuentalabel)))
                                        .addGap(59, 59, 59))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bgpanelLayout.createSequentialGroup()
                                        .addGroup(bgpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(tpo_cuentalabel, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(numero_de_cuentalabel, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(bgpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bgpanelLayout.createSequentialGroup()
                                        .addComponent(general)
                                        .addGap(110, 110, 110)
                                        .addComponent(detallada))
                                    .addComponent(nivelcbx, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(descriptxt)
                                    .addComponent(num_cuentatxt, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bgpanelLayout.createSequentialGroup()
                                .addComponent(grupo_cuenta_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(grup_cuentacbx, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bgpanelLayout.createSequentialGroup()
                                .addComponent(cuenta_padre_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cuenta_padretxt, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(bgpanelLayout.createSequentialGroup()
                                .addGroup(bgpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(debitolabel)
                                    .addComponent(creditlabel)
                                    .addComponent(balancelabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(bgpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(debitotxt, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                                    .addComponent(credittxt)
                                    .addComponent(balancetxt))))
                        .addGap(35, 35, 35)
                        .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
            .addComponent(cabecera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        bgpanelLayout.setVerticalGroup(
            bgpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgpanelLayout.createSequentialGroup()
                .addComponent(cabecera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(bgpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bgpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(num_cuentatxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(numero_de_cuentalabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(descriplabel)
                    .addComponent(descriptxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bgpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(general)
                    .addComponent(detallada)
                    .addComponent(tpo_cuentalabel))
                .addGap(14, 14, 14)
                .addGroup(bgpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nivel_de_cuentalabel)
                    .addComponent(nivelcbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bgpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuenta_padre_label)
                    .addComponent(cuenta_padretxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bgpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(grupo_cuenta_label)
                    .addComponent(grup_cuentacbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bgpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(debitolabel)
                    .addComponent(debitotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bgpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creditlabel)
                    .addComponent(credittxt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bgpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(balancelabel)
                    .addComponent(balancetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bgpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarbt)
                    .addComponent(limpiarbt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salirbt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(bgpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void descriptxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptxtActionPerformed

    }//GEN-LAST:event_descriptxtActionPerformed

    private void num_cuentatxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_cuentatxtActionPerformed

        try {
            String auxnum = num_cuentatxt.getText();
            int input = Integer.parseInt(auxnum);
            if (input <= 0) {
                JOptionPane.showMessageDialog(rootPane, "El Id debe ser un número positivo intente nuevamente");
                limpiarbtActionPerformed(evt);
            } else {

                boolean encontrado = false;
                Scanner s;
                try {
                    File f = new File("C:\\Datos\\Catalogo de cuenta.txt");

                    if (!f.exists()) {
                        f.createNewFile();
                        status.setText("Creando");
                        debitotxt.setText("0");
                        credittxt.setText("0");
                        balancetxt.setText("0");

                    } else {
                        s = new Scanner(f);
                        while (s.hasNextLine() && !encontrado) {

                            String linea = s.nextLine();
                            Scanner s1 = new Scanner(linea);

                            s1.useDelimiter("\\s*;\\s*");

                            try {
                                if (input == Integer.parseInt(s1.next())) {
                                    descriptxt.setText(s1.next());
                                    String auxAc = "";
//                                    if (accout.equals(s1.next())) {
//                                        general.setSelected(true);
//                                        auxAc = "General";
//                                    } else {
//                                        detallada.setSelected(true);
//                                        auxAc = "Detalle";
//                                    }
                                    tipo = Integer.parseInt(s1.next());
                                    if (tipo == 1) {
                                        general.setSelected(true);

                                    } else {
                                        detallada.setSelected(true);
                                    }
                                    nivelcbx.setSelectedItem(s1.next());

                                    cuenta_padretxt.setText(s1.next());
                                    grup_cuentacbx.setSelectedItem(s1.next());
                                    String debito = "0.0";
                                    if (s1.hasNext()) {
                                        debito = s1.next();
                                    }

                                    String credito = "0.0";
                                    if (s1.hasNext()) {
                                        credito = s1.next();
                                    }

                                    String balance = "0.0";
                                    if (s1.hasNext()) {
                                        balance = s1.next();
                                    }

                                    debitotxt.setText(debito);
                                    credittxt.setText(credito);
                                    balancetxt.setText(balance);

                                    LineaAntigua = num_cuentatxt.getText() + " ; " + descriptxt.getText() + " ; " + tipo + " ; " + nivelcbx.getSelectedItem()
                                            + " ; " + cuenta_padretxt.getText() + " ; " + grup_cuentacbx.getSelectedItem() + " ; " + debitotxt.getText() + " ; " + credittxt.getText() + " ; " + balancetxt.getText();
                                    status.setText("Modificando");
                                    Modificar = true;
                                    encontrado = true;
                                } else {
                                    limpiarbtActionPerformed(evt);
                                    num_cuentatxt.setText(auxnum);
                                    status.setText("Creando");
                                    Modificar = false;
                                    encontrado = false;

                                    debitotxt.setText("0");
                                    credittxt.setText("0");
                                    balancetxt.setText("0");
                                }
                            } catch (Exception e) {
                                JOptionPane.showMessageDialog(this, "Error al leer el archivo", "Error", JOptionPane.ERROR_MESSAGE);
                                System.out.println(e);
                            }
                        }
                        s.close();
                        descriptxt.grabFocus();
                    }
                } catch (FileNotFoundException e) {
                    JOptionPane.showMessageDialog(this, "No se encontró el archivo", "Error", JOptionPane.ERROR_MESSAGE);
                } catch (IOException e) {
                    System.out.println("Error al crear el archivo\n" + e);
                }

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "El Numero de Cuenta  no permite carácteres, intente nuevamente...");
            limpiarbtActionPerformed(evt);
        }
    }//GEN-LAST:event_num_cuentatxtActionPerformed

    private void cuenta_padretxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuenta_padretxtActionPerformed
        grup_cuentacbx.grabFocus();

    }//GEN-LAST:event_cuenta_padretxtActionPerformed

    private void debitotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_debitotxtActionPerformed
        credittxt.grabFocus();
    }//GEN-LAST:event_debitotxtActionPerformed

    private void credittxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_credittxtActionPerformed
        balancetxt.grabFocus();

    }//GEN-LAST:event_credittxtActionPerformed

    private void balancetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balancetxtActionPerformed

    }//GEN-LAST:event_balancetxtActionPerformed

    private void guardarbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarbtActionPerformed

        if (num_cuentatxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Se debe rellenar el Num de Cuenta antes de guardar");
        } else if (descriptxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Se debe rellenar el nombre de la cuenta antes de guardar");
        } else if (!general.isSelected() && !detallada.isSelected()) {
            JOptionPane.showMessageDialog(rootPane, "Se debe elegir el tipo de cuenta antes de guardar");
        } else if (nivelcbx.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(rootPane, "Se debe rellenar elnivel de la cuenta antes de guardar");
        } else if (cuenta_padretxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Se debe rellenar la cuenta padre antes de guardar");
        } else if (grup_cuentacbx.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(rootPane, "Se debe rellenar el grupo de la cuenta  antes de guardar");
        } else {

            String numCuenta = num_cuentatxt.getText();
            String descripcion = descriptxt.getText();
            //String tipoCuenta = general.isSelected() ? "General" : "Detalle";

            if (detallada.isSelected()) {
                tipo = 0;
            } else {
                tipo = 1;
            }

            String nivelCuenta = (String) nivelcbx.getSelectedItem();
            String cuentaPadre = cuenta_padretxt.getText();
            String grupoCuenta = (String) grup_cuentacbx.getSelectedItem();
            String debito = debitotxt.getText();
            String credito = credittxt.getText();
            String balance = balancetxt.getText();
            LocalDateTime horaCreacion = LocalDateTime.now();
            DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            DateTimeFormatter timeFormatter = DateTimeFormatter.ofPattern("HH:mm:ss");
            String fechaCreacion = horaCreacion.format(dateFormatter);
            String horaCreacionFormatted = horaCreacion.format(timeFormatter);
            try {
                String nombreArchivo = "C:\\Datos\\Catalogo de cuenta.txt";
                File archivo = new File(nombreArchivo);

                boolean existeNumCuenta = false;
                String contenidoArchivo = "";
                if (archivo.exists()) {
                    contenidoArchivo = new String(Files.readAllBytes(archivo.toPath()));
                    existeNumCuenta = contenidoArchivo.contains(numCuenta);
                }

                if (existeNumCuenta) {
                    // Actualizar el registro existente
                    contenidoArchivo = contenidoArchivo.replaceAll(numCuenta + ".*", numCuenta + " ; " + descripcion + " ; " + tipo + " ; "
                            + nivelCuenta + " ; " + cuentaPadre + " ; " + grupoCuenta + " ; " + debito + " ; " + credito + " ; " + balance + " ; " + fechaCreacion + " ; " + horaCreacionFormatted);
                    FileWriter escritor = new FileWriter(nombreArchivo);
                    escritor.write(contenidoArchivo);
                    escritor.close();
                    //  status.setText("Modificando");
                } else {
                    // Agregar un nuevo registro
                    FileWriter escritor = new FileWriter(nombreArchivo, true);
                    escritor.write(numCuenta + " ; " + descripcion + " ; " + tipo + " ; "
                            + nivelCuenta + " ; " + cuentaPadre + " ; " + grupoCuenta + " ; " + debito + " ; " + credito + " ; " + balance + " ; " + fechaCreacion + " ; " + horaCreacionFormatted + "\n");
                    escritor.close();
                    //status.setText("Creando");
                }

                JOptionPane.showMessageDialog(this, "¡Datos guardados exitosamente!", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            } catch (IOException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Error al guardar los datos.", "Error", JOptionPane.ERROR_MESSAGE);
            }

        }
        limpiarbtActionPerformed(evt);
    }//GEN-LAST:event_guardarbtActionPerformed

    private void limpiarbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarbtActionPerformed
        num_cuentatxt.setText("");
        descriptxt.setText("");
        general.setSelected(true);
        grup_cuentacbx.setSelectedItem(null);
        cuenta_padretxt.setText("");
        nivelcbx.setSelectedItem(null);
        debitotxt.setText("");
        credittxt.setText("");
        balancetxt.setText("");
        general.setSelected(false);
        detallada.setSelected(false);
        gr.clearSelection();
        status.setText("");

    }//GEN-LAST:event_limpiarbtActionPerformed

    private void salirbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirbtActionPerformed

        this.dispose();
    }//GEN-LAST:event_salirbtActionPerformed

    private void cuenta_padretxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cuenta_padretxtKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();

            if (c != KeyEvent.VK_ENTER && c != KeyEvent.VK_BACK_SPACE) {
                JOptionPane.showMessageDialog(this, "Solo se aceptan numeros.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_cuenta_padretxtKeyTyped

    private void descriptxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descriptxtKeyTyped
        String allowedCharacters = "qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM";
        char c = evt.getKeyChar();

        if ((allowedCharacters.indexOf(c) == -1) && c != KeyEvent.VK_ENTER && c != KeyEvent.VK_BACK_SPACE && c != KeyEvent.VK_SPACE) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Solo se aceptan caracteres.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_descriptxtKeyTyped

    private void generalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_generalPropertyChange

        tipo = 1;

    }//GEN-LAST:event_generalPropertyChange

    private void detalladaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_detalladaPropertyChange
        tipo = 0;
    }//GEN-LAST:event_detalladaPropertyChange

    private void generalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generalActionPerformed
        if (general.isSelected()) {
            detallada.setSelected(false);
        }
    }//GEN-LAST:event_generalActionPerformed

    private void detalladaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detalladaActionPerformed
        if (detallada.isSelected()) {
            general.setSelected(false);
        }
    }//GEN-LAST:event_detalladaActionPerformed

    private void grup_cuentacbxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_grup_cuentacbxKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            guardarbt.doClick();
        }

    }//GEN-LAST:event_grup_cuentacbxKeyPressed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CatalogoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CatalogoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CatalogoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CatalogoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new CatalogoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel balancelabel;
    private javax.swing.JTextField balancetxt;
    private javax.swing.JPanel bgpanel;
    private javax.swing.JPanel cabecera;
    private javax.swing.JLabel creditlabel;
    private javax.swing.JTextField credittxt;
    private javax.swing.JLabel cuenta_padre_label;
    private javax.swing.JTextField cuenta_padretxt;
    private javax.swing.JLabel debitolabel;
    private javax.swing.JTextField debitotxt;
    private javax.swing.JLabel descriplabel;
    private javax.swing.JTextField descriptxt;
    private javax.swing.JRadioButton detallada;
    private javax.swing.JLabel encabezadolabel;
    private javax.swing.JRadioButton general;
    private javax.swing.JComboBox<String> grup_cuentacbx;
    private javax.swing.JLabel grupo_cuenta_label;
    private javax.swing.JButton guardarbt;
    private javax.swing.JButton limpiarbt;
    private javax.swing.JLabel nivel_de_cuentalabel;
    private javax.swing.JComboBox<String> nivelcbx;
    private javax.swing.JTextField num_cuentatxt;
    private javax.swing.JLabel numero_de_cuentalabel;
    private javax.swing.JButton salirbt;
    private javax.swing.JLabel status;
    private javax.swing.JLabel tpo_cuentalabel;
    // End of variables declaration//GEN-END:variables
}
