/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Mantenimiento;

import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author Dalvi
 */
public class DocumentoFrame extends javax.swing.JFrame {

   
      
    public DocumentoFrame() {
        setLocationRelativeTo(null);
        initComponents();
    }
/**
     * Creates new form DocumentoFrame
     */
         public static String LineaAntigua;
           private boolean Modificar;
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        Cabecera = new javax.swing.JPanel();
        encabezadolabel = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        codigolabel = new javax.swing.JLabel();
        codigotxt = new javax.swing.JTextField();
        descriplabel = new javax.swing.JLabel();
        descriptxt = new javax.swing.JTextField();
        guardarbt = new javax.swing.JButton();
        limpiarbt = new javax.swing.JButton();
        salirbt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Movimiento de Documento");

        bg.setBackground(new java.awt.Color(39, 38, 44));
        bg.setToolTipText("");
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cabecera.setBackground(new java.awt.Color(64, 68, 237));
        Cabecera.setToolTipText("");

        encabezadolabel.setBackground(new java.awt.Color(64, 68, 237));
        encabezadolabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        encabezadolabel.setForeground(new java.awt.Color(255, 255, 255));
        encabezadolabel.setText("Movimiento de documentos");

        javax.swing.GroupLayout CabeceraLayout = new javax.swing.GroupLayout(Cabecera);
        Cabecera.setLayout(CabeceraLayout);
        CabeceraLayout.setHorizontalGroup(
            CabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CabeceraLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(encabezadolabel)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        CabeceraLayout.setVerticalGroup(
            CabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CabeceraLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(encabezadolabel)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        bg.add(Cabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 60));

        status.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        status.setForeground(new java.awt.Color(255, 255, 255));
        status.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        bg.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 90, 30));

        codigolabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        codigolabel.setForeground(new java.awt.Color(255, 255, 255));
        codigolabel.setText("Codigo");
        bg.add(codigolabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        codigotxt.setBackground(new java.awt.Color(39, 38, 44));
        codigotxt.setForeground(new java.awt.Color(255, 255, 255));
        codigotxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        codigotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigotxtActionPerformed(evt);
            }
        });
        codigotxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codigotxtKeyTyped(evt);
            }
        });
        bg.add(codigotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 170, -1));

        descriplabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        descriplabel.setForeground(new java.awt.Color(255, 255, 255));
        descriplabel.setText("Descripcion");
        bg.add(descriplabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        descriptxt.setBackground(new java.awt.Color(39, 38, 44));
        descriptxt.setForeground(new java.awt.Color(255, 255, 255));
        descriptxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        descriptxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriptxtActionPerformed(evt);
            }
        });
        descriptxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                descriptxtKeyTyped(evt);
            }
        });
        bg.add(descriptxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 170, -1));

        guardarbt.setBackground(new java.awt.Color(64, 68, 237));
        guardarbt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        guardarbt.setForeground(new java.awt.Color(255, 255, 255));
        guardarbt.setText("Guardar");
        guardarbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarbtActionPerformed(evt);
            }
        });
        bg.add(guardarbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        limpiarbt.setBackground(new java.awt.Color(64, 68, 237));
        limpiarbt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        limpiarbt.setForeground(new java.awt.Color(255, 255, 255));
        limpiarbt.setText("Limpiar");
        limpiarbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarbtActionPerformed(evt);
            }
        });
        bg.add(limpiarbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, -1));

        salirbt.setBackground(new java.awt.Color(255, 0, 0));
        salirbt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        salirbt.setForeground(new java.awt.Color(255, 255, 255));
        salirbt.setText("Salir");
        salirbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirbtActionPerformed(evt);
            }
        });
        bg.add(salirbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codigotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigotxtActionPerformed

 String codigo = codigotxt.getText();
try {
    if (codigo.isEmpty()) {
        JOptionPane.showMessageDialog(rootPane, "El Código no puede estar vacío, intente nuevamente");
        limpiarbtActionPerformed(evt);
    } else {
        descriptxt.setEditable(true);
        guardarbt.setEnabled(true);
        boolean encontrado = false;
        Scanner s;

        try {
            File f = new File("C:\\Datos\\Mantenimiento de documento.txt");
            if (!f.exists()) {
                f.createNewFile();
                status.setText("Creando");
            } else {
                s = new Scanner(f);
                while (s.hasNextLine() && !encontrado) {
                    String lineaActual = s.nextLine();
                    Scanner s1 = new Scanner(lineaActual);

                    s1.useDelimiter("\\s*;\\s*");

                    try {
                        if (codigo.equals(s1.next())) {
                            descriptxt.setText(s1.next());
                            Modificar = true;
                            LineaAntigua = codigotxt.getText() + " ; " + descriptxt.getText() + " ; ";
                            status.setText("Modificando");
                            encontrado = true;
                        } else {
                            descriptxt.setText("");
                            Modificar = false;
                            status.setText("Creando");
                            encontrado = false;
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Error al leer el archivo", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
                s.close();
                descriptxt.grabFocus();
            }
        } catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "No se encontró el archivo", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
            System.out.println("Error: " + ex);
        }
    }
} catch (Exception e) {
    JOptionPane.showMessageDialog(rootPane, "El Código no permite caracteres, intente nuevamente...");
    limpiarbtActionPerformed(evt);
}


    }                                         

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {                                           
 
        
    }//GEN-LAST:event_codigotxtActionPerformed

    private void descriptxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptxtActionPerformed
        guardarbt.grabFocus();
    }//GEN-LAST:event_descriptxtActionPerformed

    private void limpiarbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarbtActionPerformed
        codigotxt.setText("");
        descriptxt.setText("");
        status.setText("");
    }//GEN-LAST:event_limpiarbtActionPerformed

    private void salirbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirbtActionPerformed
        this.dispose();
    }//GEN-LAST:event_salirbtActionPerformed

    private void guardarbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarbtActionPerformed
       String codigo = codigotxt.getText();
String desc = descriptxt.getText();
try {
        String nombreArchivo = "C:\\Datos\\Mantenimiento de documento.txt";
        File archivo = new File(nombreArchivo);

        boolean existeCodigoCuenta = false;
        String contenidoArchivo = "";
        if (archivo.exists()) {
            contenidoArchivo = new String(Files.readAllBytes(archivo.toPath()));
            existeCodigoCuenta = contenidoArchivo.contains(codigo);
        }
         if (existeCodigoCuenta) {
            // Actualizar el registro existente
            contenidoArchivo = contenidoArchivo.replaceAll(codigo + ".*", codigo + " ; " + desc + " ; ");
            FileWriter escritor = new FileWriter(nombreArchivo);
              escritor.write(contenidoArchivo);
            escritor.close();
            status.setText("Modificando");
        } else {
            // Agregar un nuevo registro
            FileWriter escritor = new FileWriter(nombreArchivo, true);
            escritor.write(codigo + " ; " + desc + " ; " +"\n");
            escritor.close();
            status.setText("Creando");
        }
         
             JOptionPane.showMessageDialog(this, "¡Datos guardados exitosamente!", "Éxito", JOptionPane.INFORMATION_MESSAGE);
    } catch (IOException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error al guardar los datos.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_guardarbtActionPerformed

    private void codigotxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigotxtKeyTyped
        String allowedCharacters= "qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM123456789-_";
        char c= evt.getKeyChar();
     
         
        if ((allowedCharacters.indexOf(c)==-1) && c != KeyEvent.VK_ENTER && c != KeyEvent.VK_BACK_SPACE && c!=KeyEvent.VK_SPACE) {
             evt.consume();
            JOptionPane.showMessageDialog(this, "Solo se aceptan caracteres.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_codigotxtKeyTyped

    private void descriptxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descriptxtKeyTyped
        String allowedCharacters= "qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM";
        char c= evt.getKeyChar();
     
         
        if ((allowedCharacters.indexOf(c)==-1) && c != KeyEvent.VK_ENTER && c != KeyEvent.VK_BACK_SPACE && c!=KeyEvent.VK_SPACE) {
             evt.consume();
            JOptionPane.showMessageDialog(this, "Solo se aceptan caracteres.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_descriptxtKeyTyped

    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DocumentoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DocumentoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DocumentoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DocumentoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new DocumentoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cabecera;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel codigolabel;
    private javax.swing.JTextField codigotxt;
    private javax.swing.JLabel descriplabel;
    private javax.swing.JTextField descriptxt;
    private javax.swing.JLabel encabezadolabel;
    private javax.swing.JButton guardarbt;
    private javax.swing.JButton limpiarbt;
    private javax.swing.JButton salirbt;
    private javax.swing.JLabel status;
    // End of variables declaration//GEN-END:variables
}
